version: '3'
services:
  broker:
    image: rabbitmq:3-management-alpine
    ports:
      - 15672:15672
    networks:
      - micro_scale_net

  web-app:
    build: ./web-app/
    depends_on:
      - broker
    ports:
      - "8080:8080"
    networks:
      - micro_scale_net
  
  web-ui:
    build: ./web-ui/
    volumes:
      - "web_volume:/usr/src/web/ui"

  web-server:
    build: ./web-server/
    depends_on:
      - web-app
      - web-ui
    ports:
      - "8000:80"
    networks:
      - micro_scale_net
    volumes:
      - "web_volume:/usr/src/web/ui"
      
networks:
  micro_scale_net:

volumes:
  web_volume: