version: '3'
services:
  broker:
    image: rabbitmq:3-management-alpine
    ports:
      - 15672:15672
    networks:
      - micro_scale_net

  web-app:
    build: ./web-app/
    depends_on:
      - broker
    ports:
      - "8080:8080"
    networks:
      - micro_scale_net

  web-server:
    build: ./web-server/
    depends_on:
      - web-app
    ports:
      - "8000:80"
    networks:
      - micro_scale_net
      
networks:
  micro_scale_net: